export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Around The World',
  headline: 'Gobal Reach, Individual Focus',
  description: "Working with 91 of the Fortune Global 100, as of 2021 we have made 19 consecutive appearances on the list of Forune's 'Worlds Most Admired Companies' and that is just the begining!",
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'ipsum',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Lorum Ipsum',
  headline: 'Gobal Reach, Individual Focus',
  description: "Working with 91 of the Fortune Global 100, as of 2021 we have made 19 consecutive appearances on the list of Forune's 'Worlds Most Admired Companies' and that is just the begining!",
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'ipsum',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Around The World',
  headline: 'Gobal Reach, Individual Focus',
  description: "Working with 91 of the Fortune Global 100, as of 2021 we have made 19 consecutive appearances on the list of Forune's 'Worlds Most Admired Companies' and that is just the begining!",
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'ipsum',
  dark: true,
  primary: true,
  darkText: false,
};
