export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Around The World',
  headline: 'Gobal Reach, Individual Focus',
  description: "Working with 91 of the Fortune Global 100, as of 2021 we have made 19 consecutive appearances on the list of Forune's 'Worlds Most Admired Companies' and that is just the begining!",
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'ipsum',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Culture of Equality',
  headline: 'An Unfailing Commitment To Equality',
  description: 'Accelerating equality and commiting to our poeple has never been more relevant than it is today. We do so by taking a stand against racism and empowering disability through a inclusive and accessable workplace',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-2.svg').default,
  alt: 'ipsum',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Embrace change',
  headline: 'Make Change Work For You',
  description: 'The post-digital age shows no signs of slowing down, and the need for rapid business transformation has never been greater. We meet clients wherever they are on their paths to change—in every industry across the globe—and partner with them to create lasting value.',
  buttonLabel: 'Start now',
  imgStart: false,
  img: require('../../images/svg-3.svg').default,
  alt: 'ipsum',
  dark: false,
  primary: false,
  darkText: true,
};
